### ISSUE TITLE
Please add a license to this repository

### ISSUE THREAD

**Issue by arfon** [davecoulter/YSE_PZ#12]
:wave: @davecoulter - very nice work here!

Would you be willing to add an [open source license](https://choosealicense.com/) to this repository so that potential reuse terms are more clear? Unless you have a strong opinion about this, I'd recommend adopting the BSD 3-Clause license which is popular in scientific python communities (Astropy uses this).

**Comment by djones1040** [comment]
looks like Dave took care of this a little while ago!
