### ISSUE TITLE
Documentation on Follow-up Status and Transient Status tags

### ISSUE THREAD

**Issue by Majoburo** [davecoulter/YSE_PZ#133]
### Is your proposal related to a problem?

 Have a page in read the docs dedicated to this, with categories for each of the cases and maybe a way to update the current things we are interested in.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by astrophpeter** [comment]
Thanks @Majoburo ! @astrofoley are you able to provide one liners for each of the tags and how to use them? If you can, you could just add the text here as comment and then I will add this to the documentation.

**Comment by astrofoley** [comment]
New - Object recently discovered and unsorted.  Nobody should ever manually assign something to this category.
Watch - Object that may be targeted for follow-up observations.  This is the primary category assigned during triage.
Interesting - Particularly interesting objects that may be targeted for follow-up observations.
FollowupRequested - Object with no dedicated follow-up observation yet obtained, but a request has been made.
Following - Objects actively being followed with non-survey observations.  At least one dedicated observation is necessary for this tag.
NeedsTemplate - Object with dedicated follow-up observations that will not get additional observations of the transient, but where template observations are required.
FollowupFinished - Object with dedicated follow-up observations that will not get additional observations of the transient, and no additional template observations are required.
Ignore - All objects where no follow-up observations have been obtained and none will be obtained.

**Comment by Majoburo** [comment]
- It would be good to expand in what particularly interesting means, as that may be the more subjective category.
- What does a "non-survey observation" mean?

**Comment by astrophpeter** [comment]
I've added what Ryan has to PR #134. Please take a look at the PR and suggest more additions in the comments there.

**Comment by astrophpeter** [comment]
done
