### ISSUE TITLE
Instrument and the related filters are missing 

### ISSUE THREAD

**Issue by SamLaiiii** [davecoulter/YSE_PZ#172]
**Describe the bug**
Some Instruments and filter's original data in the photometry data file are missing

**To Reproduce**
1. Go to https://ziggy.ucolick.org/yse/transient_detail/2018agk/
2. Scroll down to "Photometry"
3. Click on ‘Download Photometry’
4. Open the Photometry file
5. most of the Direct4K*4K Instruments are missing

**Expected behavior**
All the Direct4K*4K instrument data should be updated. 

**Screenshots
what I see in the photometry file(3 data for Direct 4K*4K instruments and the filters 
![Screen Shot 2022-04-28 at 4 34 04 PM](https://user-images.githubusercontent.com/100882485/165864429-556a5af5-d4f5-4d76-b6de-f87d6b490a12.png)
multiple data for Direct 4K*4K instruments and the filters 
![Screen Shot 2022-04-28 at 4 35 42 PM](https://user-images.githubusercontent.com/100882485/165864476-9c124292-80c5-4f7f-9e37-679f9e164117.png)
**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome 

**Additional context**
Other SN targets also missed some Instruments, so the system of Photometry could be updated

**Comment by astrophpeter** [comment]
this should be fixed now @SamLaiiii , im closing the issue, feel free to reopen the issue with details if it is not fixed.

**Comment by astrophpeter** [comment]
Same says this is now fixed, so I'm going to close it out.
