### ISSUE TITLE
Update Acknowledgments Page

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#180]
**Describe the bug**

The acknowledgments page is very outdated and lacking some information

**To Reproduce**
1. Go to https://ziggy.ucolick.org/yse/acknowledgements/
2. Note that the lack of references for various papers and grants.

**Expected behavior**
We should have a clear set of instructions with well-documented references if someone uses YSE-PZ or specific data from the site.

**Additional context**
It might take some time to organize all of this, but it would be good to add whatever we can as soon as possible and then update as we go.  It might make sense to add dependency bugs to this one for specific data sets, etc.

**Comment by astrophpeter** [comment]
@astrofoley, closing this for now. Feel free to reopen if you think there is more to add.
