### ISSUE TITLE
Missing "www" from TNS, trigger Chrome privacy error

### ISSUE THREAD

**Issue by stinyanont** [davecoulter/YSE_PZ#195]
This is a quick fix. When clicking on the TNS button on a transient page, the TNS URL in the new tab is, e.g., "https://wis-tns.org/object/2022frl". This triggers Chrome's Privacy error warning because the https certificate is for "www.wis-tns.org". You can click ignore to get through, but it would be nice if we don't have to. The fix would be just to add "www." into the URL.

**Comment by astrophpeter** [comment]
Thanks Kaew! 

just a note to myself:  I believe this would simply require altering line https://github.com/davecoulter/YSE_PZ/blob/f9de35aaca455f39a635c9d1122175f6261dafed/YSE_App/templates/YSE_App/transient_detail.html#L501
 I'll get to this soon :-)

**Comment by astrophpeter** [comment]
Sorted, this should be in the next deploy. I will close the issue for now, feel free to re-open if this problem persists after the next deploy :)
