### ISSUE TITLE
Cannot sort by Last Mag

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#198]
**Describe the bug**
On the dashboard, we can no longer sort by latest magnitude.

**To Reproduce**
1. Go to the main dashboard.
2. Click on "Last Mag" for any of the categories
3. You will get a 500 error

**Expected behavior**
To sort the table by that field.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari

**Additional context**
It appears that you can still sort by all other fields including "Last Obs. Date".  I imagine this bug is related to data quality.

**Comment by astrophpeter** [comment]
I believe this is the offending line of code. 

https://github.com/davecoulter/YSE_PZ/blob/f9de35aaca455f39a635c9d1122175f6261dafed/YSE_App/views.py#L238

It's refers to the data_quality_id which was changed during the last deploy

**Comment by astrophpeter** [comment]
this was fixed in PR  #199, please re-open if issue persists after next deploy.
