### ISSUE TITLE
requirements.txt is invalid

### ISSUE THREAD

**Issue by hombit** [davecoulter/YSE_PZ#231]
I'm trying to install YSE_PZ following the documentation and found that I cannot do it due to multiple invalid (outdated?) entries in `requirements.txt`:

- `astroquery==0.4.3.dev6713` not found, replacement with `<0.5` fixed it for me
- `MarkupSafe==1.0`: cannot instal due to `ImportError: cannot import name 'Feature' from 'setuptools'` (my setuptools is too new?), replacement with `<2.0` fixed it for me
- Some Django-related stuff, (`Django<3.0` fixed it for me):
```
The conflict is caused by:
    The user requested Django==2.0.4
    django-common-helpers 0.9.2 depends on Django>=1.8.0
    django-cron 0.5.1 depends on Django>=1.8.0
    django-el-pagination 3.3.0 depends on django>=1.11.0
    django-filter 2.4.0 depends on Django>=2.2
```
- `extinction` and `sncosmo` require Cython to build, adding `cython` dependency to `yse_pz.yml` worked for me

**Comment by davecoulter** [comment]
Thanks, @hombit! I wanted to let you know that we've actually refactored the install away from pip/conda and using Docker. We're very close to getting this working in our master branch, and when it is, I will contact you and can help you get the app running.

**Comment by hombit** [comment]
Thank you, having a reproducible Dockerfile would be just fine!
