### ISSUE TITLE
Duplicate Entries

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#31]
duplicate entries:
https://ziggy.ucolick.org/yse/transient_detail/10fyseglj/
https://ziggy.ucolick.org/yse/transient_detail/2020nsx/
and
https://ziggy.ucolick.org/yse/transient_detail/10fysegli/
https://ziggy.ucolick.org/yse/transient_detail/2020nsw/
https://ucsctransients.slack.com/archives/C7QJQKKH6/p1593497636173100

**Comment by djones1040** [comment]
fixed for these but unsure if the underlying issue is fixed

**Comment by astrofoley** [comment]
This might be popping up again:
https://ziggy.ucolick.org/yse/transient_detail/10gysehnh/
https://ziggy.ucolick.org/yse/transient_detail/2020ovk/

**Comment by astrofoley** [comment]
Now we are missing an entry:
https://ziggy.ucolick.org/yse/transient_detail/10gysehko/
https://ziggy.ucolick.org/yse/transient_detail/2020qda/
https://wis-tns.weizmann.ac.il/object/2020qda

**Comment by djones1040** [comment]
cron job every ~day that checks for duplicates in newish YSE objects

**Comment by astrofoley** [comment]
https://ziggy.ucolick.org/yse/transient_detail/10gysehmr/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1152639911094626600/
https://ziggy.ucolick.org/yse/transient_detail/2020qgn/

**Comment by astrofoley** [comment]
https://ziggy.ucolick.org/yse/transient_detail/10gysehnd/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1150254180042420500/
https://ziggy.ucolick.org/yse/transient_detail/2020qfz/

**Comment by djones1040** [comment]
fixed and closing for now, but can't say I did anything that will help long-term.  appears TNS uploads failed for these but the logs say they should have worked....

**Comment by astrofoley** [comment]
A new example:
https://ziggy.ucolick.org/yse/transient_detail/10gysehmn/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1153047121131515800/
https://ziggy.ucolick.org/yse/transient_detail/202qdb/

**Comment by astrofoley** [comment]
true duplicate:
https://ziggy.ucolick.org/yse/transient_detail/10hyseijb/
https://ziggy.ucolick.org/yse/transient_detail/2020rcs/

**Comment by astrofoley** [comment]
More:
https://ziggy.ucolick.org/yse/transient_detail/10hyseiwf/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1002452781182934500/
https://ziggy.ucolick.org/yse/transient_detail/2020rfw/

https://ziggy.ucolick.org/yse/transient_detail/10hysejnu/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1160725871265557100/
https://ziggy.ucolick.org/yse/transient_detail/2020rmc/

**Comment by astrofoley** [comment]
More:
https://ziggy.ucolick.org/yse/transient_detail/10HYSEjnh/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1235811581184730700/
https://ziggy.ucolick.org/yse/transient_detail/2020roe/

**Comment by astrofoley** [comment]
https://ziggy.ucolick.org/yse/transient_detail/10GYSEhlh/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1162113301271341900/
https://ziggy.ucolick.org/yse/transient_detail/2020qgk/
