### ISSUE TITLE
different spectrum than on TNS

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#34]
The spectrum on https://ziggy.ucolick.org/yse/transient_detail/2020kvl/ is different from the one on https://wis-tns.weizmann.ac.il/object/2020kvl  It looks like the YSE-PZ one is just a shorter wavelength range.

**Comment by djones1040** [comment]
surprised this bug wasn't noticed before (or maybe I ignored previous indications).  fixed bug with clobbering old spectra and uploading from TNS. still need to update on ziggy

**Comment by djones1040** [comment]
fixed, closing
