### ISSUE TITLE
clean up tags UI

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#38]
There are so many tags that it is becoming unwieldy.  It'd be nice if we had autocomplete like https://www.w3schools.com/howto/howto_js_autocomplete.asp or https://harvesthq.github.io/chosen/

And then getting rid of the drag and drop would be good.  There should still be two lists (all tags, tags applied), but maybe one can just deselect tags applied to remove them.

**Comment by djones1040** [comment]
fixed in next deploy
