### ISSUE TITLE
Clean up plotting colors

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#40]
We should have consistent colors for all similar filters.  However right now, some of the Thacher filters (like z) don't match others (like PS1).  Just making everything consistent would be really nice for visualization.

**Comment by djones1040** [comment]
I did thacher z but others can be done by changing disp_color attribute here (or copy/pasting disp_color from another filter): https://ziggy.ucolick.org/yse/admin/YSE_App/photometricband/?p=0

**Comment by astrofoley** [comment]
It'd be nice to keep this open so someone can do a deep dive.  There are things like the LCOGT u is different from most and V where most are one color but Swope is another.  This could be a good student project.

**Comment by djones1040** [comment]
yeah, support re-opening this if there's someone assigned to it since I didn't plan to do the deep dive myself.  don't want to get in the habit of allowing overwhelming numbers of open issues to hang forever as it's pretty de-motivating, gotta learn from my Asana mistakes.

**Comment by astrofoley** [comment]
Okay, I'm fine with that.  Whatever is most motivating!  But a good way to check on these things is to look at objects with a lot of data sources like https://ziggy.ucolick.org/yse/transient_detail/2020fqv/ or https://ziggy.ucolick.org/yse/transient_detail/2019yvr/  From just those, I see that the following might need updating:

Swope/Lulin V
Swift V
LCOGT V
Nickel V
LCOGT u
LCOGT B

But might be best to just get someone to figure all of this out.

**Comment by djones1040** [comment]
ha yeah I'll try and finally fix the headache of all the filter/telescope mismatches if someone can find time to clean this up down the road
