### ISSUE TITLE
Turning off points doesn't work with combination of upper limits and detections

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#41]
See https://ziggy.ucolick.org/yse/transient_detail/2020noz/  The legend shows PS1 points as triangles, but that corresponds to the limits and not the data points.  If you click on the legend to "turn off" the points, it will only turn off the limits and there is no option to turn off the detections.

**Comment by djones1040** [comment]
I think I've given up on this one as bokeh can't associate two different symbols with the same point on the interactive legend without serious hacking
