### ISSUE TITLE
Better identification of YSE objects (or maybe more generic)

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#43]
It'd be great to have a way to quickly tell if an object is a YSE object from the summary page or even detail page.  Maybe those objects have bold names.  Yes, there is a tag for YSE, but that isn't always easy to see (and not available on the summary page).

**Comment by djones1040** [comment]
done, I think.  trying something like
![image](https://user-images.githubusercontent.com/1512537/88503302-29148780-cf86-11ea-84a3-f400613c59a2.png)
