### ISSUE TITLE
QUB link and additional photometry missing

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#47]
https://ziggy.ucolick.org/yse/transient_detail/2020nrm/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1150806341085643100/

This seems to be properly matched on QUB and in the good list, so not sure why stuff isn't in YSE-PZ.

**Comment by astrofoley** [comment]
This appears to be the case for all objects recently promoted after the deep dive into the things being missed initially.

**Comment by djones1040** [comment]
yeah had to force the QUB transfer to go back two weeks and look for everything w/o recent detections.  should be fixed now
