### ISSUE TITLE
missing TNS photometry

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#48]
https://ziggy.ucolick.org/yse/transient_detail/2020ptx/
https://wis-tns.weizmann.ac.il/object/2020ptx

**Comment by djones1040** [comment]
bleh the observer uploaded the observation as flux unit = "other" so my code has no way of knowing it's a magnitude.  I think I'm going to close this out as "broken by design" though longer term it would be good to have a way of putting in photometry by hand.
