### ISSUE TITLE
Missing recent data

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#57]
It's on QUB but not YSE-PZ
https://ziggy.ucolick.org/yse/transient_detail/2020ovi/

**Comment by astrofoley** [comment]
Also:
https://ziggy.ucolick.org/yse/transient_detail/2020pix/
https://ziggy.ucolick.org/yse/transient_detail/2020rsu/
https://ziggy.ucolick.org/yse/transient_detail/2020qhn/
https://ziggy.ucolick.org/yse/transient_detail/2020rpl/
https://ziggy.ucolick.org/yse/transient_detail/2020rmo/ (just changed it to ignore)
https://ziggy.ucolick.org/yse/transient_detail/2020qzf/ (just changed it to ignore)

**Comment by astrofoley** [comment]
More (changed many to Ignore):
https://ziggy.ucolick.org/yse/transient_detail/2020sej/
https://ziggy.ucolick.org/yse/transient_detail/2020rso/
https://ziggy.ucolick.org/yse/transient_detail/2020rrr/
https://ziggy.ucolick.org/yse/transient_detail/2020rsr/
https://ziggy.ucolick.org/yse/transient_detail/2020rla/
https://ziggy.ucolick.org/yse/transient_detail/2020qxl/
https://ziggy.ucolick.org/yse/transient_detail/10HYSEkah/
https://ziggy.ucolick.org/yse/transient_detail/10HYSEjlq/

**Comment by davecoulter** [comment]
2020ovi has data it's supposed to have.

**Comment by davecoulter** [comment]
Looks like these are corrected now.
