### ISSUE TITLE
Missing QUB link

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#61]
https://ziggy.ucolick.org/yse/transient_detail/2020tol/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1160431301264401700/

https://ziggy.ucolick.org/yse/transient_detail/2020trh/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1013603060134815900/

https://ziggy.ucolick.org/yse/transient_detail/2020thy/
https://star.pst.qub.ac.uk/sne/ps1yse/psdb/candidate/1235836681273016100/

**Comment by djones1040** [comment]
wrote function to look for old events that might have been promoted recently
