### ISSUE TITLE
SALT fits off on time of max

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#91]
See https://ziggy.ucolick.org/yse/transient_detail/2021kyp/ and https://ziggy.ucolick.org/yse/transient_detail/2021lxb/
For the latter, it looks like a single ATLAS "detection" about a month before explosion might be biasing things.  Not sure about the other SN.

**Comment by djones1040** [comment]
done - weird mag_err -> flux_err conversion was throwing off tmax
